package cli

import (
	"coastal-geometry/internal/domain/coastline"
	"coastal-geometry/internal/domain/generators/koch"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

func printRootUsage(w io.Writer) {
	bin := filepath.Base(os.Args[0])
	fmt.Fprintf(w, "Использование: %s %s [flags]\n", bin, cmdSource)
	fmt.Fprintf(w, "       %s %s <command> [flags]\n", bin, cmdReal)
	fmt.Fprintf(w, "       %s %s <command> [flags]\n", bin, cmdModel)
	fmt.Fprintf(w, "       %s %s [flags]\n\n", bin, cmdAll)
	fmt.Fprintln(w, "Назначение:")
	fmt.Fprintln(w, "  проверка геометрии береговой линии, геодезическое измерение длины")
	fmt.Fprintln(w, "  и математически корректная демонстрация её фрактальных свойств.")
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Группы команд:")
	fmt.Fprintln(w, "  Утилиты источника данных:")
	fmt.Fprintf(w, "    %-18s %s\n", canonicalCommandPath(cmdSource), getCommandUX(cmdSource).Summary)
	fmt.Fprintln(w, "  Анализ реальных данных:")
	fmt.Fprintf(w, "    %-18s %s\n", canonicalCommandPath(cmdCoastline), getCommandUX(cmdCoastline).Summary)
	fmt.Fprintln(w, "  Научные модели:")
	fmt.Fprintf(w, "    %-18s %s\n", canonicalCommandPath(cmdDimension), getCommandUX(cmdDimension).Summary)
	fmt.Fprintf(w, "    %-18s %s\n", canonicalCommandPath(cmdErosion), getCommandUX(cmdErosion).Summary)
	fmt.Fprintln(w, "  Смешанный сценарий:")
	fmt.Fprintf(w, "    %-18s %s\n", cmdAll, getCommandUX(cmdAll).Summary)
	fmt.Fprintln(w, "")
	fmt.Fprintln(w, "Примеры:")
	fmt.Fprintf(w, "  %s %s\n", bin, canonicalCommandPath(cmdSource))
	fmt.Fprintf(w, "  %s %s --refresh --output ./data/snapshots\n", bin, canonicalCommandPath(cmdSource))
	fmt.Fprintf(w, "  %s %s\n", bin, canonicalCommandPath(cmdCoastline))
	fmt.Fprintf(w, "  %s %s --source-url %s\n", bin, canonicalCommandPath(cmdCoastline), coastline.DefaultCoastlineGeoJSONURL)
	fmt.Fprintf(w, "  %s %s --iterations 6 --input data/black-sea.json\n", bin, canonicalCommandPath(cmdDimension))
	fmt.Fprintf(w, "  %s %s --steps 6 --erosion-strength 80 --wave-direction 0 --wind-speed 14\n", bin, canonicalCommandPath(cmdErosion))
	fmt.Fprintf(w, "  %s all --output ./output/full-run\n", bin)
	fmt.Fprintln(w, "")
	fmt.Fprintf(w, "См. '%s %s --help', '%s %s <command> --help', '%s %s <command> --help' или '%s all --help'.\n", bin, cmdSource, bin, cmdReal, bin, cmdModel, bin)
}

func printGroupUsage(w io.Writer, group string) {
	bin := filepath.Base(os.Args[0])

	switch group {
	case cmdReal:
		fmt.Fprintf(w, "Использование: %s %s <command> [flags]\n\n", bin, cmdReal)
		fmt.Fprintln(w, "Группа:")
		fmt.Fprintln(w, "  прямые расчёты по реально загруженной береговой линии")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Команды:")
		fmt.Fprintf(w, "  %-12s %s\n", cmdCoastline, getCommandUX(cmdCoastline).Summary)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Примеры:")
		fmt.Fprintf(w, "  %s %s\n", bin, canonicalCommandPath(cmdCoastline))
		fmt.Fprintf(w, "  %s %s --source-url %s\n", bin, canonicalCommandPath(cmdCoastline), coastline.DefaultCoastlineGeoJSONURL)
		fmt.Fprintln(w, "")
	case cmdModel:
		fmt.Fprintf(w, "Использование: %s %s <command> [flags]\n\n", bin, cmdModel)
		fmt.Fprintln(w, "Группа:")
		fmt.Fprintln(w, "  научные модели геоморфологических процессов, построенные от загруженной базовой геометрии")
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Команды:")
		fmt.Fprintf(w, "  %-12s %s\n", cmdDimension, getCommandUX(cmdDimension).Summary)
		fmt.Fprintf(w, "  %-12s %s\n", cmdErosion, getCommandUX(cmdErosion).Summary)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Примеры:")
		fmt.Fprintf(w, "  %s %s --iterations 6 --output ./output/dimension\n", bin, canonicalCommandPath(cmdDimension))
		fmt.Fprintf(w, "  %s %s --steps 6 --erosion-strength 80 --wave-direction 0\n", bin, canonicalCommandPath(cmdErosion))
	}
}

func printCommandUsage(w io.Writer, command string) {
	bin := filepath.Base(os.Args[0])
	usagePath := canonicalCommandPath(command)

	switch command {
	case cmdSource:
		fmt.Fprintf(w, "Использование: %s %s [flags]\n\n", bin, usagePath)
		ux := getCommandUX(command)
		fmt.Fprintln(w, "Загружает выбранный источник береговой линии по той же схеме cache/remote/fallback, выводит метаданные набора и сохраняет сырой snapshot локально.")
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "Режим: %s\n", ux.Mode)
		fmt.Fprintf(w, "Примечание: %s\n", ux.RuntimeNote)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Флаги:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        путь к локальному JSON/GeoJSON-файлу береговой линии, используемому как fallback (по умолчанию %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --source-url string")
		fmt.Fprintf(w, "        удалённый URL GeoJSON-источника береговой линии (по умолчанию %q; пустая строка отключает HTTP-загрузку)\n", coastline.DefaultCoastlineGeoJSONURL)
		fmt.Fprintln(w, "  --refresh")
		fmt.Fprintln(w, "        принудительно обновить кэш удалённого GeoJSON перед сохранением snapshot")
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintf(w, "        путь к snapshot-файлу или директории (по умолчанию ./%s)\n", coastline.DefaultCoastlineSnapshotDir)
	case cmdAll:
		fmt.Fprintf(w, "Использование: %s %s [flags]\n\n", bin, cmdAll)
		ux := getCommandUX(command)
		fmt.Fprintln(w, "Запускает полный научный сценарий: проверку геометрии, анализ фрактальной размерности и физически обоснованную модель волновой эрозии.")
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "Режим: %s\n", ux.Mode)
		fmt.Fprintf(w, "Примечание: %s\n", ux.RuntimeNote)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Флаги:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        путь к локальному JSON/GeoJSON-файлу береговой линии, используемому как fallback (по умолчанию %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --source-url string")
		fmt.Fprintf(w, "        удалённый URL GeoJSON-источника береговой линии (по умолчанию %q; пустая строка отключает HTTP-загрузку)\n", coastline.DefaultCoastlineGeoJSONURL)
		fmt.Fprintln(w, "  --refresh")
		fmt.Fprintln(w, "        принудительно обновить кэш удалённого GeoJSON перед запуском")
		fmt.Fprintln(w, "  --iterations int")
		fmt.Fprintf(w, "        максимальное число итераций organic Koch (0-%d)\n", koch.MaxIterations)
		fmt.Fprintln(w, "  --seed int")
		fmt.Fprintln(w, "        seed для генерации organic-береговой линии")
		fmt.Fprintln(w, "  --angle-jitter float")
		fmt.Fprintln(w, "        максимальное случайное отклонение угла в градусах")
		fmt.Fprintln(w, "  --height-jitter float")
		fmt.Fprintln(w, "        максимальное случайное отклонение высоты как доля")
		fmt.Fprintln(w, "  --erosion-strength float")
		fmt.Fprintln(w, "        базовый отступ берега в метрах за шаг (0 отключает)")
		fmt.Fprintln(w, "  --steps int")
		fmt.Fprintln(w, "        число шагов волновой эрозии")
		fmt.Fprintln(w, "  --wave-direction float")
		fmt.Fprintln(w, "        направление волн, градусов от севера")
		fmt.Fprintln(w, "  --wind-speed float")
		fmt.Fprintln(w, "        скорость ветра, м/с")
		fmt.Fprintln(w, "  --bathymetry string")
		fmt.Fprintln(w, "        путь к JSON-файлу батиметрии")
		fmt.Fprintln(w, "  --lithology string")
		fmt.Fprintln(w, "        путь к JSON-файлу литологии")
		fmt.Fprintln(w, "  --enable-lithology")
		fmt.Fprintln(w, "        включить модуляцию по литологии")
		fmt.Fprintln(w, "  --target-years int")
		fmt.Fprintln(w, "        целевой период моделирования в годах")
		fmt.Fprintln(w, "  --years-per-step float")
		fmt.Fprintln(w, "        лет за шаг моделирования")
		fmt.Fprintln(w, "  --storm-probability float")
		fmt.Fprintln(w, "        вероятность шторма за шаг [0-1]")
		fmt.Fprintln(w, "  --storm-intensity float")
		fmt.Fprintln(w, "        множитель интенсивности шторма [1.0-10.0]")
		fmt.Fprintln(w, "  --sea-level-rise float")
		fmt.Fprintln(w, "        подъём уровня моря, м/год")
		fmt.Fprintln(w, "  --enable-seasonality")
		fmt.Fprintln(w, "        включить сезонные колебания")
		fmt.Fprintln(w, "  --seasonal-phase float")
		fmt.Fprintln(w, "        фаза сезонности, радианы [0-2π]")
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        директория для выходных визуализаций (по умолчанию: ./output)")
	case cmdCoastline:
		fmt.Fprintf(w, "Использование: %s %s [flags]\n\n", bin, usagePath)
		ux := getCommandUX(command)
		fmt.Fprintln(w, "Проверяет геометрию береговой линии, измеряет её длину геодезически и сохраняет SVG-отчёт.")
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "Режим: %s\n", ux.Mode)
		fmt.Fprintf(w, "Примечание: %s\n", ux.RuntimeNote)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Флаги:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        путь к локальному JSON/GeoJSON-файлу береговой линии, используемому как fallback (по умолчанию %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --source-url string")
		fmt.Fprintf(w, "        удалённый URL GeoJSON-источника береговой линии (по умолчанию %q; пустая строка отключает HTTP-загрузку)\n", coastline.DefaultCoastlineGeoJSONURL)
		fmt.Fprintln(w, "  --refresh")
		fmt.Fprintln(w, "        принудительно обновить кэш удалённого GeoJSON перед запуском")
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        путь к SVG-файлу или директории вывода (по умолчанию: ./output)")
	case cmdDimension:
		fmt.Fprintf(w, "Использование: %s %s [flags]\n\n", bin, usagePath)
		ux := getCommandUX(command)
		fmt.Fprintln(w, "Считает эмпирическую box-counting размерность по organic-итерациям роста береговой линии, проверяет сходимость и сохраняет `dimension_iter_0..N.svg`.")
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "Режим: %s\n", ux.Mode)
		fmt.Fprintf(w, "Примечание: %s\n", ux.RuntimeNote)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Флаги:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        путь к локальному JSON/GeoJSON-файлу береговой линии, используемому как fallback (по умолчанию %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --source-url string")
		fmt.Fprintf(w, "        удалённый URL GeoJSON-источника береговой линии (по умолчанию %q; пустая строка отключает HTTP-загрузку)\n", coastline.DefaultCoastlineGeoJSONURL)
		fmt.Fprintln(w, "  --refresh")
		fmt.Fprintln(w, "        принудительно обновить кэш удалённого GeoJSON перед запуском")
		fmt.Fprintln(w, "  --iterations int")
		fmt.Fprintf(w, "        максимальное число итераций organic Koch (0-%d)\n", koch.MaxIterations)
		fmt.Fprintln(w, "  --seed int")
		fmt.Fprintln(w, "        seed для генерации organic-береговой линии")
		fmt.Fprintln(w, "  --angle-jitter float")
		fmt.Fprintln(w, "        максимальное случайное отклонение угла в градусах")
		fmt.Fprintln(w, "  --height-jitter float")
		fmt.Fprintln(w, "        максимальное случайное отклонение высоты как доля")
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        директория для выходных визуализаций (по умолчанию: ./output)")
	case cmdErosion:
		fmt.Fprintf(w, "Использование: %s %s [flags]\n\n", bin, usagePath)
		ux := getCommandUX(command)
		fmt.Fprintln(w, "Запускает направленную волновую эрозию: оценивает fetch по сектору волн, вычисляет экспозицию сегментов и сильнее размывает открытые мысы, чем защищённые бухты.")
		fmt.Fprintln(w, "")
		fmt.Fprintf(w, "Режим: %s\n", ux.Mode)
		fmt.Fprintf(w, "Примечание: %s\n", ux.RuntimeNote)
		fmt.Fprintln(w, "")
		fmt.Fprintln(w, "Флаги:")
		fmt.Fprintln(w, "  --input string")
		fmt.Fprintf(w, "        путь к локальному JSON/GeoJSON-файлу береговой линии, используемому как fallback (по умолчанию %q)\n", coastline.DefaultCoastlineJSONPath)
		fmt.Fprintln(w, "  --source-url string")
		fmt.Fprintf(w, "        удалённый URL GeoJSON-источника береговой линии (по умолчанию %q; пустая строка отключает HTTP-загрузку)\n", coastline.DefaultCoastlineGeoJSONURL)
		fmt.Fprintln(w, "  --refresh")
		fmt.Fprintln(w, "        принудительно обновить кэш удалённого GeoJSON перед запуском")
		fmt.Fprintln(w, "  --steps int")
		fmt.Fprintln(w, "        число шагов волновой эрозии")
		fmt.Fprintln(w, "  --erosion-strength float")
		fmt.Fprintln(w, "        базовый отступ берега в метрах за шаг до учёта fetch и экспозиции")
		fmt.Fprintln(w, "  --wave-direction float")
		fmt.Fprintln(w, "        направление, откуда приходят волны, в градусах по часовой стрелке от севера")
		fmt.Fprintln(w, "  --wind-speed float")
		fmt.Fprintln(w, "        скорость ветра, управляющая энергией волн, в м/с")
		fmt.Fprintln(w, "  --fetch-spread float")
		fmt.Fprintln(w, "        полуширина оффшорного сектора, по которому рассчитывается fetch, в градусах")
		fmt.Fprintln(w, "  --fetch-samples int")
		fmt.Fprintln(w, "        число лучей для оценки fetch и угла падения волн")
		fmt.Fprintln(w, "  --max-fetch-km float")
		fmt.Fprintln(w, "        верхнее ограниение расстояния fetch в километрах")
		fmt.Fprintln(w, "  --depth-scale float")
		fmt.Fprintln(w, "        масштаб nearshore openness, используемый как прокси глубины, в метрах")
		fmt.Fprintln(w, "  --exposure-power float")
		fmt.Fprintln(w, "        степень нелинейного усиления для косинуса угла падения волны")
		fmt.Fprintln(w, "  --bathymetry string")
		fmt.Fprintln(w, "        путь к JSON-файлу батиметрии с точками {lat,lon,depth} (пусто = использовать геометрический proxy)")
		fmt.Fprintln(w, "  --lithology string")
		fmt.Fprintln(w, "        путь к JSON-файлу литологии с данными о сопротивлении пород (пусто = использовать дефолтный профиль)")
		fmt.Fprintln(w, "  --enable-lithology")
		fmt.Fprintln(w, "        включить модуляцию эрозии по литологии (retreat /= сопротивление породы)")
		fmt.Fprintln(w, "  --seed int")
		fmt.Fprintln(w, "        seed для воспроизводимой микронеровности эрозии")
		fmt.Fprintln(w, "  --target-years int")
		fmt.Fprintln(w, "        целевой период моделирования в годах (0 использует шаги)")
		fmt.Fprintln(w, "  --years-per-step float")
		fmt.Fprintln(w, "        лет за шаг моделирования (требует target-years)")
		fmt.Fprintln(w, "  --storm-probability float")
		fmt.Fprintln(w, "        вероятность шторма за шаг [0-1]")
		fmt.Fprintln(w, "  --storm-intensity float")
		fmt.Fprintln(w, "        множитель интенсивности шторма [1.0-10.0]")
		fmt.Fprintln(w, "  --sea-level-rise float")
		fmt.Fprintln(w, "        подъём уровня моря, м/год")
		fmt.Fprintln(w, "  --enable-seasonality")
		fmt.Fprintln(w, "        включить сезонные колебания")
		fmt.Fprintln(w, "  --seasonal-phase float")
		fmt.Fprintln(w, "        фаза сезонности, радианы [0-2π]")
		fmt.Fprintln(w, "  --output string")
		fmt.Fprintln(w, "        директория для выходных визуализаций (по умолчанию: ./output)")
	}
}
